name: "CLA"
on:
  pull_request_target:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: "CLA Assistant"
        if: >-
          github.event_name == 'pull_request_target' || 
          (github.event_name == 'issue_comment' && github.event.issue.pull_request && 
          (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'))
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          PERSONAL_ACCESS_TOKEN: ${{ steps.create_token.outputs.token }}
        with:
          path-to-signatures: 'signatures-v3.json'
          path-to-document: 'https://github.com/open-domains/register/blob/main/terms.md'
          branch: 'main'
          allowlist: od-bot,bot*,kyro3400
          remote-organization-name: 'open-domains'
          remote-repository-name: 'cla'
          lock-pullrequest-aftermerge: false

      - name: add CLA signed
        uses: actions-ecosystem/action-add-labels@v1
        if: >-
          github.event_name == 'pull_request_target' || 
          (github.event_name == 'issue_comment' && github.event.issue.pull_request && 
          (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'))
        with:
          labels: "CLA Signed"
          github_token: ${{ steps.create_token.outputs.token }}

      - name: remove CLA required
        uses: actions-ecosystem/action-remove-labels@v1
        if: >-
          github.event_name == 'pull_request_target' || 
          (github.event_name == 'issue_comment' && github.event.issue.pull_request && 
          (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'))
        with:
          labels: "CLA Required"
          github_token: ${{ steps.create_token.outputs.token }}    

      - if: ${{ failure() }}
        name: Add CLA required
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "CLA Required"
          github_token: ${{ steps.create_token.outputs.token }}
